server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de tu React App
    location / {
        root /var/www/frontend;
        try_files $uri /index.html;
    }

    # Redirige todas las llamadas a /api hacia tu backend de Laravel
    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://app:9000; # 'app' es el nombre del servicio de PHP
        proxy_set_header Host $host;
    }
}